services:
  phinx:
    build: .
    volumes:
      - .:/src
    command: bash
    environment:
      - TESTS_PHINX_DB_ADAPTER_MYSQL_HOST=mysql
      - TESTS_PHINX_DB_ADAPTER_POSTGRES_HOST=postgres
  mysql:
    image: mysql:9.1
    environment:
      - MYSQL_DATABASE=phinx
      - MYSQL_ROOT_PASSWORD=root

  postgres:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=phinx
      - POSTGRES_PASSWORD=postgres
